### ISSUE TITLE
每个视频播放完毕自动提交答题么

### ISSUE THREAD

**Issue by banduoba** [HollowMan6/ChaoXing-ErYa-Wisdom-Tree-Lessons-Helper#1]
怎么设置每个视频播放完毕自动答题呢?验证码好像跳不过

**Comment by HollowMan6** [comment]
如果想要专业一点的工具，建议你看看这里：[cxmooc-tools](https://github.com/CodFrm/cxmooc-tools)
这个工具做得比较成熟，我这里只是一个简单的脚本，没想过要做题库。这个工具里有验证码自动打码功能。
