### ISSUE TITLE
一个网页中有多个视频要看的情况下只能看最后一个

### ISSUE THREAD

**Issue by eiheiheiOwO** [HollowMan6/ChaoXing-ErYa-Wisdom-Tree-Lessons-Helper#2]

**Comment by HollowMan6** [comment]
您好，我不知道您说的是超星尔雅还是智慧树的问题，我这里默认将其当为超星尔雅的问题。

同时，您说的问题您未描述清楚，所以我也不清楚，是指的一个页面上同时存在多个视频，无法播放该页面上的所有视频？还是说存在多个标签，我的脚本跳转有问题？

如果是后者，我刚刚将此BUG修复，请查看我的[最新发布](https://github.com/HollowMan6/ChaoXing-ErYa-Wisdom-Tree-Lessons-Helper/releases/tag/v5.2)，或者直接下载我的仓库文件。

如果是前者，此脚本是能够在一个页面上同时存在多个视频时同时播放该页面上的所有视频，如果您确认是此问题，请提供详细描述，比如说页面的截图。谢谢！

此issue现在我默认为已解决状态，如有问题欢迎继续提issue。
